name: typescript-action
description: Template of TypeScript Action

inputs:
  datadog-api-key:
    description: Datadog API key
    required: true
  datadog-site:
    description: Datadog Site name if different than datadoghq.com.
    required: false
  metrics-csv-path:
    description: Glob pattern to CSV file(s) for metrics
    required: false
  metric-name:
    description: Name of metric
    required: false
  metric-type:
    description: Type of metric (count, gauge or rate)
    required: false
  metric-value:
    description: Value of metric
    required: false
  metric-tags:
    description: Tags of metric (multi-line of KEY:VALUE) (optional)
    required: false
  event-title:
    description: Title of event
    required: false
  event-text:
    description: Text of event
    required: false
  event-alert-type:
    description: Alert type of event (error, warning or info) (optional)
    required: false
  event-tags:
    description: Tags of event (multi-line of KEY:VALUE) (optional)
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
