name: ts

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/ts.yaml
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/ts.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .node-version
      - run: npm install -g corepack
      - run: corepack enable
      - run: pnpm i
      - run: pnpm test
      - run: pnpm build

      - name: int128/send-datadog-action
        uses: ./
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          metric-name: send_datadog_action.run
          metric-type: count
          metric-value: 1
          metric-tags: |
            github.event_name:${{ github.event_name }}
            github.repository:${{ github.repository }}
            github.actor:${{ github.actor }}
          event-title: GitHub Actions ${{ github.event_name }}
          event-text: workflow ${{ github.workflow }}, job ${{ github.job }}
          event-alert-type: warning
          event-tags: |
            github.event_name:${{ github.event_name }}
            github.repository:${{ github.repository }}
            github.actor:${{ github.actor }}

      - name: int128/send-datadog-action (simple csv)
        uses: ./
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          metrics-csv-path: tests/fixtures/metrics.csv

      - name: int128/send-datadog-action (use-header-tags csv)
        uses: ./
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          metrics-csv-path: tests/fixtures/metrics_with_header_tags.csv
          metrics-csv-format: use-header-tags

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .node-version
      - run: npm install -g corepack
      - run: corepack enable
      - run: pnpm i
      - run: pnpm run check
      - uses: int128/update-generated-files-action@ce932483d2788cdb57a29349376a8b36ed85eea3 # v2.99.0
