name: ts

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/ts.yaml
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/ts.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - run: npm install -g corepack
      - run: corepack enable
      - run: pnpm i
      - run: pnpm test
      - run: pnpm build

      - name: int128/send-datadog-action
        uses: ./
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          metric-name: send_datadog_action.run
          metric-type: count
          metric-value: 1
          metric-tags: |
            github.event_name:${{ github.event_name }}
            github.repository:${{ github.repository }}
            github.actor:${{ github.actor }}
          event-title: GitHub Actions ${{ github.event_name }}
          event-text: workflow ${{ github.workflow }}, job ${{ github.job }}
          event-alert-type: warning
          event-tags: |
            github.event_name:${{ github.event_name }}
            github.repository:${{ github.repository }}
            github.actor:${{ github.actor }}

      - name: int128/send-datadog-action (simple csv)
        uses: ./
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          metrics-csv-path: tests/fixtures/metrics.csv

      - name: int128/send-datadog-action (use-header-tags csv)
        uses: ./
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          metrics-csv-path: tests/fixtures/metrics_with_header_tags.csv
          metrics-csv-format: use-header-tags

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - run: npm install -g corepack
      - run: corepack enable
      - run: pnpm i
      - run: pnpm run check
      - uses: int128/update-generated-files-action@cf464119e796f83eac0a9e85021c568269aa9e1a # v2.103.0
